name = "lean4demo"
version = "0.1.0"
defaultTargets = ["lean4demo"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[lean_lib]]
name = "Lean4demo"

[[lean_exe]]
name = "lean4demo"
root = "Main"
