graph LR
  subgraph 其它
    CS学习规划["CS学习规划"]
    index["index"]
    使用指南["使用指南"]
    后记["后记"]
    好书推荐["好书推荐"]
    CS50["CS50"]
    CMake["CMake"]
    Docker["Docker"]
    Emacs["Emacs"]
    Git["Git"]
    GitHub["GitHub"]
    GNU_Make["GNU_Make"]
    LaTeX["LaTeX"]
    Scoop["Scoop"]
    thesis["thesis"]
    tools["tools"]
    Vim["Vim"]
    workflow["workflow"]
    信息检索["信息检索"]
    翻墙["翻墙"]
    Data100["Data100"]
    CS189["CS189"]
    ML["ML"]
    CMU10-414["CMU10-414"]
    CSE234["CSE234"]
    EML["EML"]
    MLC["MLC"]
    CMU10-708["CMU10-708"]
    CS229M["CS229M"]
    roadmap["roadmap"]
    STA4273["STA4273"]
    STAT8201["STAT8201"]
    CMU11-785["CMU11-785"]
    CS224w["CS224w"]
    CS230["CS230"]
    CS231["CS231"]
    CS285["CS285"]
    EECS498-007["EECS498-007"]
    LHY["LHY"]
    MIT6-7960["MIT6-7960"]
    NYU-DLSP21["NYU-DLSP21"]
    MIT6_S184["MIT6.S184"]
    CMU11-667["CMU11-667"]
    CMU11-711["CMU11-711"]
    CMU11-868["CMU11-868"]
    CMU15-779["CMU15-779"]
    EE16["EE16"]
    signal["signal"]
    Signals_and_Systems_AVO["Signals_and_Systems_AVO"]
    CSE365["CSE365"]
    CSE466["CSE466"]
    MIT6_858["MIT6.858"]
    SEEDLabs["SEEDLabs"]
    DeCal["DeCal"]
    MIT-Missing-Semester["MIT-Missing-Semester"]
    Duke-Coursera-Intro-C["Duke-Coursera-Intro-C"]
    AUT1400["AUT1400"]
    CS106["CS106"]
    CS3110["CS3110"]
    Haskell-MOOC["Haskell-MOOC"]
    MIT 6_092["MIT 6.092"]
    CS50P["CS50P"]
    MIT6_100L["MIT6.100L"]
    cs220["cs220"]
    cs431["cs431"]
    Cambridge-Semantics["Cambridge-Semantics"]
    CS242["CS242"]
    NJU-SoftwareAnalysis["NJU-SoftwareAnalysis"]
    PKU-SoftwareAnalysis["PKU-SoftwareAnalysis"]
  end
  subgraph Web
    CS142["CS142"]
    CS571["CS571"]
    fullstackopen["fullstackopen"]
    mitweb["mitweb"]
  end
  subgraph 人工智能
    CS188["CS188"]
    Neural Networks：Zero to Hero["Neural Networks：Zero to Hero"]
  end
  subgraph 体系结构
    CA["CA"]
    CS61C["CS61C"]
    DDCA["DDCA"]
    N2T["N2T"]
    NandToTetris["NandToTetris"]
  end
  subgraph 并行计算
    CS149["CS149"]
  end
  subgraph 分布式系统
    MIT6_824["MIT6.824"]
  end
  subgraph 操作系统
    CS162["CS162"]
    HITOS["HITOS"]
    MIT6_S081["MIT6.S081"]
    NJUOS["NJUOS"]
  end
  subgraph 数学
    information["information"]
    MITLA["MITLA"]
    MITmaths["MITmaths"]
    6_042J["6.042J"]
    convex["convex"]
    CS126["CS126"]
    CS70["CS70"]
    numerical["numerical"]
    The_Information_Theory_Pattern_Recognition_and_Neural_Networks["The_Information_Theory_Pattern_Recognition_and_Neural_Networks"]
    CS231n["CS231n"]
    概率论["概率论"]
    编译原理基础["编译原理基础"]
    微积分["微积分"]
    线性代数["线性代数"]
  end
  subgraph 数据库
    15445["15445"]
    15799["15799"]
    CS122["CS122"]
    CS186["CS186"]
    CS346["CS346"]
  end
  subgraph 算法
    6_006["6.006"]
    6_046["6.046"]
    Algo["Algo"]
    CS170["CS170"]
    CS161["CS161"]
  end
  subgraph 数据结构
    CS61B["CS61B"]
  end
  subgraph AI/ML
    CS229["CS229"]
    CS224n["CS224n"]
  end
  subgraph AI
    AICS["AICS"]
  end
  subgraph 系统基础
    MIT6_1600["MIT6.1600"]
    CS110["CS110"]
    CSAPP["CSAPP"]
  end
  subgraph 程序设计
    CS61A["CS61A"]
  end
  subgraph 编译原理
    CS143["CS143"]
    CS420["CS420"]
    NJU-Compilers["NJU-Compilers"]
    PKU-Compilers["PKU-Compilers"]
    SJTU-Compilers["SJTU-Compilers"]
    USTC-Compilers["USTC-Compilers"]
  end
  subgraph 图形学
    15462["15462"]
    CS148["CS148"]
    GAMES101["GAMES101"]
    GAMES103["GAMES103"]
    GAMES202["GAMES202"]
  end
  subgraph 图形
    USTC ComputerGraphics["USTC ComputerGraphics"]
  end
  subgraph 计算机网络
    CS144["CS144"]
    CS168["CS168"]
    topdown["topdown"]
  end
  subgraph 软件工程
    17803["17803"]
    6031["6031"]
    CS169["CS169"]
  end
  CSAPP --> MIT6_S081
  NandToTetris --> MIT6_S081
  MIT6_S081 --> MIT6_824
  CS162 --> MIT6_824
  CSAPP --> CS162
  CS61C --> CS162
  CS61C --> CS144
  topdown --> CS144
  CS61A --> CS169
  CS61B --> CS169
  CS61B --> CS186
  CS61C --> CS186
  CS229 --> CS224n
  CS231n --> CS224n
  线性代数 --> CS229
  概率论 --> CS229
  编译原理基础 --> CS143
  CS143 --> CS420
  CSAPP --> CS149
  CS110 --> CS149
  CS148 --> 15462
  线性代数 --> 15462
  线性代数 --> GAMES101
  GAMES101 --> GAMES202
  15462 --> GAMES202
  CSAPP --> CS110
